### ISSUE TITLE
biteopt stopping criteria

### ISSUE THREAD

**Issue by avaneev** [dietmarwo/fast-cma-es#10]
I see that biteopt stopping criteria is fixed

if (stallCount > 64*dim) {
                stop = 2;
                break;
            }

it puts BiteOpt at a considerable disadvantage on complex problems. This should be switchable, and off by default. Also it would be better for stopping criteria specified as "stopc*64*dim", where "stopc" is an integer>0

Also please specify BiteOpt version in each instance its results are mentioned.

**Comment by avaneev** [comment]
StallCount stopping criteria should not be used in comparisons at all, it's for research cycle.

**Comment by dietmarwo** [comment]
Ok, will make the stop criteria configurable for the next release. For comparisons removing the stopping criteria may sometimes harm the results, when it will reduce the number of retries - same as increasing the maximal number of evaluations. Making it configurable seems the best solutions.

>stopping criteria specified as "stopc64dim", where "stopc" is an integer>0.

What exactly does this mean?

**Comment by dietmarwo** [comment]
Pushed the changes - and verified that https://github.com/dietmarwo/fcmaes-java, the java version has configurable BiteOpt stop criteria already implemented. Will soon release to pip - after some more tests. Version 1.3.18 will include the change. 
Default is now: No premature stopping to avoid disadvantages for comparisons. But at 
https://github.com/dietmarwo/fast-cma-es/blob/73afbb643590553b4937a3b9340bf4d8385f3cb8/examples/noisy_tsp.py#L78
premature stopping definitiely helps in comparisons.

**Comment by dietmarwo** [comment]
1.3.18 released on pip (do pip install fcmaes --upgrade).
New version contains the fix. 
New parameter is called stall_iterations defaulting to 0 - no premature stopping. 
Optimization is stopped now if stallCount > stall_iterations*dim:

           if (stall_iterations > 0 && stallCount > stall_iterations*dim) {
                stop = 2;
                break;
            }

**Comment by avaneev** [comment]
Thank you!

**Comment by avaneev** [comment]
However, the criteria should be (multiply by 64):
```
if (stall_iterations > 0 && stallCount > stall_iterations*64*dim) {
            stop = 2;
            break;
        }
```
