### ISSUE TITLE
Problem with running on Mac OS X

### ISSUE THREAD

**Issue by Slamim8** [dietmarwo/fast-cma-es#11]
Hey, I am trying to use fcmaes on my MacBook, but when importing GTOP problems from fcmaes.astro I face this error:
no suitable image was found.  Did find:
	/Users/maryamsmacbookpro/opt/anaconda3/lib/python3.9/site-packages/fcmaes/lib/libgtoplib.dll: unknown file type, first eight bytes: 0x4D 0x5A 0x90 0x00 0x03 0x00 0x00 0x00

I have searched a lot but none of the solutions did work. I'd be very thankful if you help me!

**Comment by dietmarwo** [comment]
Thank you for your support in creating the macos library file and fixing the remaining bugs. 
I uploaded a new version (1.3.19) to pip.
Please try 'pip install fcmaes --upgrade' on your mac and check if the installed version works. 
If yes, we can close this issue.

**Comment by Slamim8** [comment]
You're welcome.
Thanks for your valuable cooperation, advice, and support. 
Yes, It works on my machine and the issue is resolved! :))

Bests, 
Maryam
