### ISSUE TITLE
Usage for diploma thesis

### ISSUE THREAD

**Issue by LucaGrbt** [dietmarwo/fast-cma-es#16]
Dear Mr. Wolf,

I`m a student from Kaiserslautern, Germany and I`d like to involve your seemingly well done piece of work here in my diploma thesis. It is about direct benchmarking quantum solver results with proper up-to-date solvers on common hardware. As I read about MIT license here, am I allowed to use your code here to work with and publish it. Of course you as author will be called in the final thesis then. In that case, please tell me the correct source to mention for the job shop solver.

With kind regards,
Luca Graebenteich

**Comment by LucaGrbt** [comment]
Now sorry for my late reply,

please read the paper of my thesis' supervisor and colleagues: 

https://link.springer.com/article/10.1007/s11740-022-01145-8

I'm not very familiar with the quantum computing part of the project. It was my task to do proper research on the field of optimzations research and implement algorithms for direct comparison by multi objective optimization. The project is being run on a quantum annealer of the company DWave (USA). 

Within the next semester or years there will also be GA variations to be compared with the results. I by myself am a little restricted due to the fact that I'm from a pure engineering major and the whole field of optimization was completely new to me and far too complex to learn in just about 6-8 months.

If you are more interested in the quantum side of the project, please contact me via svengraebenteich@gmail.com . I would friendly forward you to the chair. I'm not too familiar about how cooperations work in the academic area.

I'm also not too aware how well connected the project is with the Smart Factory at our University in Kaiserslautern. I just know their are some ressources being built to encounter the topics of Industry 4.0 in particular.

**Comment by dietmarwo** [comment]
This is about the application of a quantum algorithm to the flexible job shop problem. As I have shown in 
https://github.com/dietmarwo/fast-cma-es/blob/master/tutorials/JobShop.adoc , fcmaes can also be applied to this problem. I also show results for MK11-MK15, bigger variants of the benchmark problems used in your paper (MK1-MK10).  Your results are good, but are they significantly better than what can be achieved by a non-quantum algorithm?
Interesting would also be if the quantum algorithm scales: Do the solutions improve if more time is invested?
The fcmaes MOO algorithm (modecpp)  can for instance find a makespan=208 solution when we invest one hour. Still worse than the best known solution (197), but better than what the quantum algorithm found.
