### ISSUE TITLE
JSON of the employee scheduling example

### ISSUE THREAD

**Issue by ogencoglu** [dietmarwo/fast-cma-es#20]
Thank you for the OptaPy comparison for Employee Scheduling problem.

Can you upload the JSON representation of the employee scheduling problem mentioned in the tutorial so we do not have to run the OptaPy solution. 

Or even better would be to have an example with one of the [nurse rostering benchmark](http://www.schedulingbenchmarks.org/nrp/) problems.

**Comment by dietmarwo** [comment]
Was busy with other tasks, will add more examples, but probably not before October.
