### ISSUE TITLE
illegal hardware instruction when importing mode on mac M1

### ISSUE THREAD

**Issue by TimotF** [dietmarwo/fast-cma-es#21]
**Minimal steps to reproduce :** 
run python in a terminal (I am currently using python 3.9.7)
in the python terminal, run `from fcmaes import mode` 

**Error :** 
`zsh: illegal hardware instruction  python`

**Side note :** 
if I run the python terminal from a bash terminal (instead of zsh), I get 
`Illegal instruction: 4`

If yo have any idea on how to fix this, that would be great :)

**Comment by TimotF** [comment]
It appears that this bug occurs in the x86 version of Python (emulated with Rosetta 2), but not in the arm64 version. If this information is helpful to anyone, here's a method to use the arm64 version of Python:

```
# creating the python env
arch -arm64 python3.11 -m venv env
source env/bin/activate
pip install fcmaes
```

The import works with this Python version, but I am unable to test the execution because my implementation relies on pymeshlab, which is currently not compatible with arm64 Python...

**Comment by dietmarwo** [comment]
Unfortunately I don't have a Mac available. Is there a crosscompiler on Linux for MAC-ARM so I can generate the required shared libraries? Otherwise on arm64 only the Python implementations of the algorithms can be used.
