### ISSUE TITLE
Missing library loguru when installing fcmaes 1.6.3 with pip

### ISSUE THREAD

**Issue by NavidHedjazian** [dietmarwo/fast-cma-es#22]
Required package loguru is not installed automatically by pip in the 1.6.3 version.

I tested with python 3.9 and 3.11:

starting from a fresh virtual environment
```
~$ pip install fcmaes
~$ pip list
Package       Version
------------- -------
fcmaes        1.5.9
joblib        1.3.2
numpy         1.26.0
pip           23.2.1
scikit-learn  1.3.1
scipy         1.11.3
setuptools    68.2.0
threadpoolctl 3.2.0
wheel         0.41.2

>>> from fcmaes import cmaes
ModuleNotFoundError: No module named 'loguru'
```

Although loguru is specified as "required" in setup.py, it is not mentioned in the wheel on PyPi.
In the METADATA file of the wheel, we can read the dependencies:
"Requires-Dist: numpy
Requires-Dist: scipy
Requires-Dist: scikit-learn
Requires-Dist: threadpoolctl"

Of course, for now, I could install loguru manually to solve the issue.

I suppose the same issue will arise with missing numba package.

**Comment by dietmarwo** [comment]
Uploaded 1.6.4.
Now I see

Requires-Dist: numpy
Requires-Dist: scipy
Requires-Dist: scikit-learn
Requires-Dist: threadpoolctl
Requires-Dist: numba
Requires-Dist: loguru

Should be fixed. Thks for the hint.
