### ISSUE TITLE
v1.6.10 doesn't compile

### ISSUE THREAD

**Issue by rujialiu** [dietmarwo/fast-cma-es#25]
Dear Dietmar Wolz,

First of all, thanks for the awesome library! However, I cannot compile v1.6.10.

In this commit:
https://github.com/dietmarwo/fast-cma-es/commit/ce911dcad7a899a20a2e29d5bfcbd06448e4739f

EigenRand seems to be replaced by pcg-cpp, but nothing is changed in `_fcmaescpp/include/evaluator.h`. I suspect you forgot to commit this file?

Thanks in advance!

**Comment by dietmarwo** [comment]
Sorry, forget to uodate evaluator.h, I pushed the updated file now. 
You need https://github.com/imneme/pcg-cpp/tree/master/include 
for compilation.

**Comment by rujialiu** [comment]
I can confirm that the updated file works perfected on my environment (Win10, Though I had to make a few minor modifications to make it compile with MSVC). Thanks!

**Comment by wolf75222** [comment]
**Still some erros** 

$ ls
acmaesoptimizer.cpp  biteoptimizer.cpp  CMakeFiles           CMakeLists.txt  csmaoptimizer.cpp  deoptimizer.cpp     include     lcldeoptimizer.cpp  Makefile           o
ascent.cpp           CMakeCache.txt     cmake_install.cmake  crfmnes.cpp     daoptimizer.cpp    gcldeoptimizer.cpp  install.sh  ldeoptimizer.cpp    modeoptimizer.cpp  pgpe.cpp
$ ./install.sh
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cosmos/zeus_devdev/fast-cma-es/_fcmaescpp
[  7%] Building CXX object CMakeFiles/acmalib.dir/acmaesoptimizer.cpp.o
[ 15%] Building CXX object CMakeFiles/acmalib.dir/pgpe.cpp.o
[ 23%] Building CXX object CMakeFiles/acmalib.dir/deoptimizer.cpp.o
[ 30%] Building CXX object CMakeFiles/acmalib.dir/daoptimizer.cpp.o
In file included from /home/cosmos/zeus_devdev/fast-cma-es/_fcmaescpp/daoptimizer.cpp:18:
/home/cosmos/zeus_devdev/fast-cma-es/_fcmaescpp/include/LBFGSB.h:10:10: erreur fatale: LBFGSpp/Param.h : Aucun fichier ou dossier de ce type
 #include "LBFGSpp/Param.h"
          ^~~~~~~~~~~~~~~~~
compilation terminée.
`

**Comment by rujialiu** [comment]
In case you wondered why I didn't have these problems: I manually downloaded LBFGSpp and removed ascent related things as I know I don't need them. But it's definitely better to make it working out-of-the-box without any manual tweak.

BTW: I have encountered zero issue since I start using this. The optimizers always work great. Thank you again @dietmarwo
