### ISSUE TITLE
How to get the Hessian matrix OR parameters uncertainties?

### ISSUE THREAD

**Issue by Landau1908** [dietmarwo/fast-cma-es#26]
Is the Hessian matrix of the objective function OR parameters uncertainties avaliable?
fcmase returns scipy.optimize.OptimizeResult, which contains attribute hess.
However, I indeed can't retrieve the hessian.
Thanks.

**Comment by dietmarwo** [comment]
No, scipy.optimize.OptimizeResult is used for compatibility with scipy. 
fcmaes uses derivative free algos which don't use the Hessian. Derivative free
https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.differential_evolution.html
will also not provide a Hessian.
