### ISSUE TITLE
cannot find dll file on windows

### ISSUE THREAD

**Issue by lxy764139720** [dietmarwo/fast-cma-es#4]
I'm using "evolopy" project on my windows 10, but I got this error in "fcmaes":
```
FileNotFoundError: Could not find module 'D:\anaconda\envs\ML\lib\site-packages\fcmaes\lib\libgtoplib.dll' (or one of its dependencies).
```
However, I truly found this file in the right directory. Is that a bug on Windows? How can I deal with it? Must I use linux instead? Thx.

**Comment by dietmarwo** [comment]
From https://github.com/dietmarwo/fast-cma-es :
"install C++ runtime libraries https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads"
did you try that? Its probably an indirect dependency not fulfilled.
